export const categoriesData = [
  { id: "hair", name: "Hair Care", description: "Hair cutting, styling, and treatments" },
  { id: "facial", name: "Facial & Skincare", description: "Facial treatments and skincare services" },
  { id: "massage", name: "Massage", description: "Relaxing and therapeutic massages" },
  { id: "makeup", name: "Makeup & Beauty", description: "Professional makeup and beauty services" },
  { id: "nails", name: "Nail Care", description: "Manicure, pedicure, and nail art" },
  { id: "spa", name: "Spa Treatments", description: "Full body spa and wellness treatments" },
]

export const salonsData = [
  {
    id: "1",
    name: "Glamour Studio",
    description:
      "Premium salon offering luxury hair and beauty services with experienced stylists and modern facilities.",
    address: "123 Beauty Street, Bandra West, Mumbai",
    openingHours: "09:00",
    closingHours: "21:00",
    rating: 4.8,
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    services: [
      {
        id: "s1",
        title: "Hair Cut & Style",
        description: "Professional haircut with styling",
        price: 800,
        duration: 60,
        categoryId: "hair",
      },
      {
        id: "s2",
        title: "Hair Color",
        description: "Full hair coloring service",
        price: 2500,
        duration: 180,
        categoryId: "hair",
      },
      {
        id: "s3",
        title: "Facial Treatment",
        description: "Deep cleansing facial treatment",
        price: 1200,
        duration: 90,
        categoryId: "facial",
      },
      {
        id: "s4",
        title: "Manicure & Pedicure",
        description: "Complete nail care service",
        price: 600,
        duration: 120,
        categoryId: "nails",
      },
    ],
  },
  {
    id: "2",
    name: "Bliss Spa & Salon",
    description: "Relaxing spa and salon experience with natural treatments and wellness services.",
    address: "456 Wellness Avenue, Juhu, Mumbai",
    openingHours: "10:00",
    closingHours: "20:00",
    rating: 4.6,
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    services: [
      {
        id: "s5",
        title: "Swedish Massage",
        description: "Relaxing full body massage",
        price: 2000,
        duration: 90,
        categoryId: "massage",
      },
      {
        id: "s6",
        title: "Anti-Aging Facial",
        description: "Advanced anti-aging treatment",
        price: 1800,
        duration: 120,
        categoryId: "facial",
      },
      {
        id: "s7",
        title: "Hair Spa",
        description: "Nourishing hair treatment",
        price: 1000,
        duration: 75,
        categoryId: "hair",
      },
    ],
  },
  {
    id: "3",
    name: "Style Hub",
    description: "Modern salon with trendy styles and affordable prices for all your beauty needs.",
    address: "789 Fashion Road, Andheri East, Mumbai",
    openingHours: "09:30",
    closingHours: "21:30",
    rating: 4.4,
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    services: [
      {
        id: "s8",
        title: "Bridal Makeup",
        description: "Complete bridal makeup package",
        price: 5000,
        duration: 240,
        categoryId: "makeup",
      },
      {
        id: "s9",
        title: "Hair Straightening",
        description: "Professional hair straightening",
        price: 3000,
        duration: 150,
        categoryId: "hair",
      },
      {
        id: "s10",
        title: "Body Massage",
        description: "Therapeutic body massage",
        price: 1500,
        duration: 60,
        categoryId: "massage",
      },
    ],
  },
]
